STM scheduler logic without mv-datastructure and validation
danielxiangzl/libra pull request #10
Opened 2021-06-29 21:54 UTC by danielxiangzl

## Motivation

(Write your motivation for proposed changes here.)

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

## Test Plan

(Share your test plan here. If you changed code, please provide us with clear instructions for verifying that your changes work.)

## Related PRs

(If this PR adds or changes functionality, please take some time to update the docs at https://github.com/libra/libra/developers.libra.org, and link to your PR here.)

2021-06-29 22:01 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +        let mut vec: Vec<DepStruct> = Vec::new();
Can we initialize this once in the constructor? Since we are actually guaranteed that vectors will be empty when the block is done.

..Can txn_num change? maybe we allocate till the max.

2021-06-29 22:02 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        match shared_tx_idx_ring_buffer.pop() {
We should be careful of this potentially becoming a contention bottleneck later on, but even if it does it's solvable. Just something to watch out for.

2021-06-29 22:03 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        if (status == FLAG_EXECUTED) || !(idx < stop_when.load(Ordering::Relaxed)) {
I believe we should never be here if it's already executed, so should this be an assert?

2021-06-29 22:05 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                                let status = deps_mapping[dep_id].status.load(Ordering::Relaxed);
Let's do a trick here. Grab the status, and check before line 194 if it's executed (and continue). Otherwise, as here.
This way if it was already executed, we avoid locking (txn right now can never go from executed to not executed).

2021-06-29 22:07 UTC, gelash reviewed
Great work. I added some targeted comments, but high-level, I'd now try to move these things (dep structures, logic for getting the next task, logic for postponing a task) into a separate scheduler module.
Could start with wrapping the new code (dependency structure & related), and then also pass the (A).

2021-06-29 22:47 UTC, danielxiangzl commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        if (status == FLAG_EXECUTED) || !(idx < stop_when.load(Ordering::Relaxed)) {
Resolved

2021-06-29 22:48 UTC, danielxiangzl commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                                let status = deps_mapping[dep_id].status.load(Ordering::Relaxed);
Resolved

2021-06-30 17:02 UTC, gelash commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +pub struct DepStruct {
don't forget padding

2021-07-01 21:46 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                                    skip = true;
skip might be confusing with the skip indicator baseline has for entries.

2021-07-01 21:55 UTC, gelash commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> -                                let status = deps_mapping[dep_id].status.load(Ordering::Relaxed);
let's keep this as well and do
if status == FLAG_EXECUTED {
    continue;
}

2021-07-01 21:58 UTC, gelash commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +            if status == FLAG_EXECUTED {
i'd slightly prefer the way you had before, i.e. if NOT_EXECUTED, add it to the deps. we will return true immediately afterwards anyway.

2021-07-01 22:08 UTC, gelash commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +                txn_set = deps.clone();
even though the thread will have to do O(|deps|) work, we should try to not do it while holding the lock - so try to swap the vectors here (idk if mem::swap does it, or we can wrap it in a box or smt -whatever the rusty way is, no need for arcs since we are protected by a lock).

2021-07-01 22:10 UTC, gelash commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +            self.txn_id_buffer.push(ids);
let's sort ids before we push them into txn_buffer - if it doesn't introduce overhead now, it can actually be beneficial in other scenarios.

2021-07-01 22:23 UTC, gelash reviewed
optional: if we can find a simple unit test case for some of the scheduler logic (even single threaded), would be great to add one.

2021-07-02 03:06 UTC, gelash commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +                txn_set = deps.clone();
oh actually neither box nor mutex guard allow moving out, so the way to do this would be to wrap the vector inside an option, so Arc<Mutex<Option<Vec<usize>>>>. Please add a comment here or in the description to explain why we do it.

2021-07-07 00:49 UTC, runtian-zhou requested changes
Looks good to me in general! The major question I have is whether we should populate the dependency structure prior to thread execution because the dependency won't be changed during execution (assuming no unestimated write). Doing things up front might give us a cleaner code structure.

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/data_cache.rs
> +                if self.as_ref().write(k, version, val.clone()).is_err() {
Revert this change?

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/data_cache.rs
> +    pub fn will_read_block_return_version(&self, access_path: &AccessPath) -> (bool, usize) {
Return `Option<Version>` instead?

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/mod.rs
> +pub mod scheduler;
Love this!

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +        // let deps_mapping = Arc::new(DepMapping::new(num_txns));
Feel free to remove existing code!

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        if !(idx < scheduler.stop_when.load(Ordering::Relaxed)) {
Can this logic be integrated into the `next_task`?

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        let mut postpone = false;
Can probably simplify the logic here using `Option` chaining. Also probably don't need the `postpone` flag as you can do `spin_loop_hint` by replacing `break` with `continue`.

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                                    scheduler.stop_when.fetch_min(idx, Ordering::SeqCst);
Would be nice if we can hide the `stop_when` field and implement the method in `Scheduler`

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +    pub fn new() -> Self {
Was wondering if we should pass dependencies here as they are not going to change throughout execution. We can leave it as is tho if we would like to get this first iteration in.

2021-07-07 00:49 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +    pub fn next_task(&self) -> Option<usize> {
Nice API!

2021-07-08 23:35 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/data_cache.rs
> +    pub fn will_read_block_return_version(&self, access_path: &AccessPath) -> Option<usize> {
Can youl add a comment saying that return `Some(version)` when `access_path` is blocked by transaction `version`?

2021-07-08 23:35 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                        // If the txn has unresolved dependency, adds the txn to deps_mapping of its dependency (only the first one) and continue
Have you tried `cargo fmt`?

2021-07-08 23:35 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/parallel_transaction_executor.rs
> +                                    scheduler.set_txn_num(idx);
I would name it as `set_stop_version` or sth. The `set_txn_num` doesn't sounds quite intuitive.

2021-07-08 23:35 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +    pub fn update_read_deps(&self, idx: usize, dep_id: usize) -> Option<bool> {
Can you add comments to what each of these function do?

2021-07-08 23:35 UTC, runtian-zhou commented on language/diem-vm/src/parallel_executor/scheduler.rs
> +            let mut deps = self.deps_mapping[dep_id].dep_vec.lock().unwrap();
Can this unwrap hits an error? If so/not can you provide some explanantion there (same for the next unwrap)

2021-07-08 23:35 UTC, runtian-zhou commented on language/e2e-testsuite/proptest-regressions/tests/account_universe/bad_transaction.txt
> +# Seeds for failure cases proptest has generated in the past. It is
Need to remove this(and all those txt) files :)

2021-07-12 21:41 UTC, closed without merging